// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpqrukaybzrzagxojzdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcXJ1a2F5YnpyemFneG9qemRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTI0NzUsImV4cCI6MjA2NDc2ODQ3NX0.RDjyKbRr-ZZKgRJVScpQa8OR5eB3bfUgjFAl_V9-k6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);